- id: turn_off_lights_at_1
  alias: "Wyłącz światła o 1"
  trigger:
    - platform: time
      at: "01:00:00"
  action:
    - service: switch.turn_off
      entity_id: switch.livingroom_main_light, switch.bathroom_main_light, switch.kitchen_main_light

- id: send_pushbullet_notification_washmachine_finished
  alias: "Pralka skończyła pracę"
  trigger:
    - platform: state
      entity_id: binary_sensor.bathroom_washmachine
      from: 'on'
      to: 'off'
  action:
    - service: notify.hassio
      data:
        title: "Pranie zakończone"
        message: "Pralka zakończyła pranie."