homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 51.0905
  longitude: 17.0373
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 124
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Warsaw
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://192.168.1.106:3218

mqtt:
  broker: 192.168.1.106

notify:
  - name: Hassio
    platform: pushbullet
    api_key: o.TKzVieNdLRdqjeddv95l4WXgPP52DeT0

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr
  - platform: mqtt
    state_topic: "home/livingroom/temperature"
    unique_id: home_livingroom_sensor_temperature
    name: "Temperatura"
    unit_of_measurement: '°C'
  - platform: mqtt
    state_topic: "home/livingroom/humidity"
    unique_id: home_livingroom_sensor_humidity
    name: "Wilgotność"
    unit_of_measurement: '%'
  - platform: mqtt
    state_topic: "garden/zone1/ground_humidity"
    unique_id: garden_zone1_ground_humidity
    name: "Wilgotność gleby"
    unit_of_measurement: '%'
  - platform: template
    sensors:
      last_run:
        friendly_name: "Ostatnie uruchomienie"
        value_template: '{{ (as_timestamp(states.switch.garden_zone1_sprinkler.last_changed)) | timestamp_custom("%A, %d %h %H:%M") }}'
  
switch:
  - platform: mqtt
    unique_id: home_livingroom_main_light
    name: "Światło"
    state_topic: "home/livingroom/lightswitch"
    command_topic: "home/livingroom/lightswitch/set"
    payload_on: "1"
    payload_off: "0"
  - platform: mqtt
    unique_id: home_kitchen_main_light
    name: "Światło"
    state_topic: "home/kitchen/lightswitch"
    command_topic: "home/kitchen/lightswitch/set"
    payload_on: "1"
    payload_off: "0"    
  - platform: mqtt
    unique_id: home_bathroom_main_light
    name: "Światło"
    state_topic: "home/bathroom/lightswitch"
    command_topic: "home/bathroom/lightswitch/set"
    payload_on: "1"
    payload_off: "0"
  - platform: mqtt
    unique_id: garden_zone_1_sprinkler
    name: "Spryskiwcz"
    state_topic: "garden/zone1/sprinkler"
    command_topic: "garden/zone1/sprinkler/set"
    payload_on: "1"
    payload_off: "0"
    
binary_sensor:
  - platform: mqtt
    unique_id: home_livingroom_binary_sensor_maindoor
    name: "Drzwi"
    state_topic: "home/maindoor"
    payload_on: "1"
    payload_off: "0"
    qos: 0
    device_class: door
  - platform: mqtt
    unique_id: home_bathroom_binary_sensor_washmachine
    name: "Pralka"
    state_topic: "home/bathroom/washmachine"
    payload_on: "1"
    payload_off: "0"
    qos: 0
    device_class: moving

input_number:
  garden_zone1_sprinkler_duration:
    name: "Czas trwania"
    initial: 10
    min: 1
    max: 60
    step: 1
    unit_of_measurement: "Minuty"

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
